CREATE DATABASE QL_SV
USE QL_SV
DECLARE @HOTEN NVARCHAR(20),@TUOI INT
--SET @HOTEN='NGUYỄN VĂN KHÁNH'
--SET @TUOI=20
SELECT @HOTEN='NGUYỄN VĂN KHÁNH',@TUOI=20
--SELECT @HOTEN,@TUOI
PRINT @HOTEN
PRINT @TUOI

CREATE TABLE SINHVIEN(
MASV CHAR(20),
HOTEN NVARCHAR(50),
NGSINH DATE,
DIEMTB FLOAT,
CONSTRAINT PK_SINHVIEN PRIMARY KEY(MASV)
)
INSERT INTO SINHVIEN VALUES
('SV001',N'NGUYỄN THỊ NHI','2000/3/3',8.9),
('SV002',N'NGUYỄN THỊ ANH','2010/2/23',5),
('SV003',N'LÂM VĂN KHÁNH','2004/11/5',7.8),
('SV004',N'TẠ ANH NGỌC','2008/5/30',6.9),
('SV005',N'DƯƠNG KHANG HẢI','2012/6/12',2.9),
('SV006',N'KHA NHƯ HOÀNG','1995/9/22',9),
('SV007',N'VĂN NGỌC ANH','1999/4/11',8),
('SV008',N'ĐẶNG NHƯ LỘC','2001/1/9',6)

DECLARE @A NVARCHAR(50),@B DATE
SET @A=(SELECT HOTEN
FROM SINHVIEN
WHERE MASV='SV001')
SET @B=(SELECT NGSINH
FROM SINHVIEN
WHERE MASV='SV001')
PRINT @A
PRINT @B
--DECLARE @A NVARCHAR(50),@B DATE
SELECT @A=HOTEN,@B=NGSINH
FROM SINHVIEN
WHERE MASV='SV002'
SELECT @A,@B

DECLARE @C FLOAT
SET @C=(
SELECT DIEMTB
FROM SINHVIEN
WHERE MASV='SV001'
)
IF(@C<5)
PRINT N'YẾU'
ELSE IF(@C<7)
PRINT N'TRUNG BÌNH'
ELSE IF(@C<8)
PRINT N'KHÁ'
ELSE 
PRINT N'GIỎI'



DECLARE @D DATE
SET @D=(
SELECT NGSINH
FROM SINHVIEN
WHERE MASV='SV001'
)
IF((YEAR(GETDATE())-YEAR(@D))>30)
BEGIN
DECLARE @HOTEN1 NVARCHAR(40),@TUOI1 DATE,@DIEMTB FLOAT
SELECT @HOTEN1=HOTEN,@TUOI1=NGSINH,@DIEMTB=DIEMTB
--SELECT HOTEN,NGSINH,DIEMTB
FROM SINHVIEN
WHERE  MASV='SV001'
END
ELSE
PRINT 'SINH NAY DUOI 30 TUOI'


DECLARE @E FLOAT
SET @E=(
SELECT DIEMTB
FROM SINHVIEN
)

IF EXISTS(
SELECT DIEMTB
FROM SINHVIEN
WHERE DIEMTB>5
)
SELECT * 
FROM SINHVIEN
WHERE DIEMTB>5
ELSE 
PRINT 'KO CO SV NAO DUOI TRUNG BINH'
