CREATE DATABASE QL_KHACHHANG
GO
USE QL_KHACHHANG
GO

CREATE TABLE KHACHHANG
(
    MAKHACHHANG CHAR(10),
    TENCONGTY NVARCHAR(40),
    TENGIAODICH NVARCHAR(40),
    DIACHI NVARCHAR(50),
    EMAIL CHAR(30),
    DIENTHOAI CHAR(12),
    FAX CHAR(20),
    CONSTRAINT PK_KHACHHANG PRIMARY KEY(MAKHACHHANG)
)

CREATE TABLE NHANVIEN
(
    MANHANVIEN CHAR(10),
    HO NVARCHAR(40),
    TEN NVARCHAR(10),
    NGAYSINH DATE,
    NGAYLAMVIEC DATE,
    DIACHI NVARCHAR(50),
    DIENTHOAI CHAR(12),
    LUONGCOBAN FLOAT,
    PHUCAP FLOAT,
    CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANHANVIEN)
)

CREATE TABLE TAIXE
(
    MATAIXE CHAR(10),
    HOTEN NVARCHAR(50),
    BIENSOXE CHAR(15),
    LOAIXE NVARCHAR(20),
    DIENTHOAI CHAR(12),
    TRANGTHAI NVARCHAR(20) DEFAULT N'Rảnh',
    CONSTRAINT PK_TAIXE PRIMARY KEY(MATAIXE),
    CONSTRAINT UQ_TAIXE_BIENSOXE UNIQUE (BIENSOXE),
    CONSTRAINT CK_TAIXE_LOAIXE CHECK (LOAIXE IN (N'Xe máy', N'Xe tải', N'Container'))
)

CREATE TABLE DONDATHANG
(
    SOHOADON CHAR(20),
    MATAIXE CHAR(10),
    MAKHACHHANG CHAR(10),
    MANHANVIEN CHAR(10),
    NGAYDATHANG DATE,
    NGAYGIAOHANG DATE,
    NGAYCHUYENHANG DATE,
    NOIGIAOHANG NVARCHAR(50),
    CONSTRAINT PK_DONDATHANG PRIMARY KEY(SOHOADON),
    CONSTRAINT FK_DONDATHANG_NHANVIEN FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN),
    CONSTRAINT FK_DONDATHANG_KHACHHANG FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG),
    CONSTRAINT FK_DONDATHANG_TAIXE FOREIGN KEY (MATAIXE) REFERENCES TAIXE(MATAIXE)
)

CREATE TABLE LOAIHANG
(
    MALOAIHANG CHAR(20),
    TENLOAIHANG NVARCHAR(40),
    CONSTRAINT PK_LOAIHANG PRIMARY KEY(MALOAIHANG)
)

CREATE TABLE NHACUNGCAP
(
    MACONGTY CHAR(10),
    TENCONGTY NVARCHAR(40),
    TENGIAODICH NVARCHAR(20),
    DIACHI NVARCHAR(50),
    DIENTHOAI CHAR(12),
    CONSTRAINT PK_NHACUNGCAP PRIMARY KEY(MACONGTY)
)

CREATE TABLE MATHANG
(
    MAHANG CHAR(20),
    TENHANG NVARCHAR(50),
    MACONGTY CHAR(10),
    MALOAIHANG CHAR(20),
    SOLUONG INT,
    DONVITINH CHAR(10),
    GIAHANG MONEY,
    CONSTRAINT PK_MATHANG PRIMARY KEY(MAHANG),
    CONSTRAINT FK_MATHANG_NHACUNGCAP FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP(MACONGTY),
    CONSTRAINT FK_MATHANG_LOAIHANG FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG)
)

CREATE TABLE CHITIETDATHANG
(
    SOHOADON CHAR(20),
    MAHANG CHAR(20),
    GIABAN MONEY,
    SOLUONG INT,
    MUCGIAMGIA FLOAT,
    CONSTRAINT PK_CHITIETDATHANG PRIMARY KEY(MAHANG,SOHOADON),
    CONSTRAINT FK_CT_DONDATHANG FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG(SOHOADON),
    CONSTRAINT FK_CT_MATHANG FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG)
)

CREATE TABLE DANHGIA
(
    MADANHGIA CHAR(10),
    MAKHACHHANG CHAR(10),
    MATAIXE CHAR(10),
    SOHOADON CHAR(20),
    DIEMSO INT CHECK (DIEMSO BETWEEN 1 AND 5), -- 1 đến 5 sao
    NHANXET NVARCHAR(200),
    CONSTRAINT PK_DANHGIA PRIMARY KEY (MADANHGIA),
    CONSTRAINT FK_DANHGIA_KH FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG),
    CONSTRAINT FK_DANHGIA_TX FOREIGN KEY (MATAIXE) REFERENCES TAIXE(MATAIXE),
    CONSTRAINT FK_DANHGIA_DH FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG(SOHOADON)
)

ALTER TABLE KHACHHANG
ADD CONSTRAINT UQ_KHACHHANG_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_KHACHHANG_EMAIL CHECK (EMAIL LIKE '%@%.%')

ALTER TABLE NHANVIEN
ADD CONSTRAINT CK_NHANVIEN_LUONG CHECK (LUONGCOBAN >= 0 AND PHUCAP >= 0)

ALTER TABLE CHITIETDATHANG
ADD CONSTRAINT CK_CHITIET_SOLUONG CHECK (SOLUONG > 0 AND GIABAN >= 0 AND MUCGIAMGIA BETWEEN 0 AND 100)

ALTER TABLE DONDATHANG
ADD CONSTRAINT CK_DONDATHANG_NGAY CHECK (NGAYDATHANG <= NGAYGIAOHANG)
